### ISSUE TITLE
Error: The name of the current PowerShell host is: 'Visual Studio Code Host'. PwshSyntaxHighlight.psd1' requires the following PowerShell host: 'ConsoleHost'

### ISSUE THREAD

**Issue by netcorefan1** [ShaunLawrie/PwshSyntaxHighlight#5]
I get the error in the title when trying to access the module from vs code.
It works if I comment the `PowerShellHostName` field of the manifest:
```
Description = 'A code block renderer for PowerShell code in the terminal'
PowerShellVersion = '5.0'
# PowerShellHostName = 'ConsoleHost'
RootModule = 'PwshSyntaxHighlight'
```
Is the host name necessary?
Also, I'm not sure if setting PowerShellVersion to 5.0 will cause PS 7 running in "legacy mode" without taking advantage of its performance improvements. Shouldn't be better to comment this too and leave PS auto adapt based on the host machine?

**Comment by ShaunLawrie** [comment]
Good points, I'll take a look thanks. I didn't know about legacy mode - Is there a way to detect it?

**Comment by ShaunLawrie** [comment]
I just removed the restriction anyway. It should be sorted if you run `Update-Module PwshSyntaxHighlight` or install the latest from PSGallery 😁 Thanks

**Comment by netcorefan1** [comment]
> I just removed the restriction anyway. It should be sorted if you run `Update-Module PwshSyntaxHighlight` or install the latest from PSGallery 😁 Thanks

Many thanks! It works now!

> Good points, I'll take a look thanks. I didn't know about legacy mode - Is there a way to detect it?

Well, I also don't know about any legacy mode. I just assumed (**and I could be perfectly wrong**) that restricting to version 5.0 may cause PowerShell 7 to run in some sort of compatibility mode. It may possible (**and I could be wrong again**) that on 5.0 will be loaded the .Net Framework or  .Net Standard runtime rather than .Net 7 (and yes, this is like night and day). As far as I know, compatibility breaks if you use 5.0 dedicated modules not yet ported to the new PS 7. From what I see, the library  don't even use external modules, so I think we should be fine.
